### ISSUE TITLE
Errors in Etherpad

### ISSUE THREAD

**Issue by DanielHabenicht** [marcelklehr/ep_push2delete#11]
When installed the following error pops up: 
```
[ERROR] console - DOUBLE SETTLE BUG IN HOOK FUNCTION (plugin: ep_push2delete, function name: /opt/etherpad-lite/node_modules/ep_push2delete/index:handleMessage, hook: handleMessage): Attempt to resolve via returned value but it already resolved via callback. Ignoring this attempt to resolve.
```
as well as 
```
Jul 19 09:43:17 jitsi-v2 node[113989]: [2022-07-19 09:43:17.586] [WARN] console - padRemove padID context property is deprecated; use pad.id instead
Jul 19 09:43:17 jitsi-v2 node[113989]:     at Object.get padID [as padID] (/opt/etherpad-lite/src/node/db/Pad.js:567:9)
Jul 19 09:43:17 jitsi-v2 node[113989]:     at Object.exports.padRemove [as hook_fn] (/opt/etherpad-lite/node_modules/ep_comments_page/index.js:20:49)
Jul 19 09:43:17 jitsi-v2 node[113989]:     at /opt/etherpad-lite/src/static/js/pluginfw/hooks.js:272:18
Jul 19 09:43:17 jitsi-v2 node[113989]:     at new Promise (<anonymous>)
Jul 19 09:43:17 jitsi-v2 node[113989]:     at callHookFnAsync (/opt/etherpad-lite/src/static/js/pluginfw/hooks.js:235:16)
Jul 19 09:43:17 jitsi-v2 node[113989]:     at /opt/etherpad-lite/src/static/js/pluginfw/hooks.js:350:54
Jul 19 09:43:17 jitsi-v2 node[113989]:     at Array.map (<anonymous>)
Jul 19 09:43:17 jitsi-v2 node[113989]:     at Object.exports.aCallAll (/opt/etherpad-lite/src/static/js/pluginfw/hooks.js:350:13)
Jul 19 09:43:17 jitsi-v2 node[113989]:     at Pad.remove (/opt/etherpad-lite/src/node/db/Pad.js:565:18)
Jul 19 09:43:17 jitsi-v2 node[113989]:     at Object.exports.handleMessage [as hook_fn] (/opt/etherpad-lite/node_modules/ep_push2delete/index.js:39:9)
```

Are you open for PR or is this not maintained anymore?

**Comment by marcelklehr** [comment]
> Are you open for PR or is this not maintained anymore?

I'd rather avoid maintenance, but I'm happy to add you as a maintainer, if you like.

**Comment by gerardo-navarro** [comment]
@DanielHabenicht Have you found a solution for this. I am seeing the same error message in my etherpad-lite setup.

**Comment by DanielHabenicht** [comment]
No we simply did not use it but instead automatically deleted the pad.

**Comment by nwittstruck** [comment]
Just in case anyone sees this in the future: 
The return for handleMessage should only be triggered once - so either retun false, or execute the callback. Not both. You can fix this by removing these [two lines](https://github.com/marcelklehr/ep_push2delete/blob/master/index.js#L25-L26) 
```
callback(false);
return false;
```
and replace them with:
```
return callback(false);
```
